---
- hosts: localhost
  gather_facts: no
  vars:
    mylist:
      - hello
      - world
  tasks:
    - name: Lookup via lookup function
      debug:
        msg: "{{ lookup('indexed_items',mylist) }}"
    - name: Lookup via with_ keyword
      debug:
        msg: "{{ item }}"
      with_indexed_items: "{{ mylist }}"
